In [8]:
import pandas as pd

In [9]:
df = pd.read_csv("books.csv")
df

,avaibility,description,price,title,upc
0,19,Aaron Ledbetter’s future had been planned out ...,17.46,Set Me Free,ce6396b0f23f6ecc
1,19,Libertarianism isn't about winning elections; ...,51.33,Libertarianism for Beginners,a18a4f574854aced
2,19,"“Wherever you go, whatever you do, just . . . ...",45.17,It's Only the Himalayas,a22124811bfa8350
3,19,This is the never-before-told story of the mus...,57.25,Our Band Could Be Your Life: Scenes from the A...,deda3e61b9514b83
4,19,This book is an important and complete collect...,20.66,Shakespeare's Sonnets,30a7f60cd76ca58c
...,...,...,...,...,...
995,1,"To the dismay of religious leaders, study afte...",28.42,Choosing Our Religion: The Spiritual Lives of ...,a812f6969ddf3e39
996,1,Meet Bridget Jones—a 30-something Singleton wh...,29.82,Bridget Jones's Diary (Bridget Jones #1),a2b4b685dfa94733
997,1,***BONUS CONTENT: The first two chapters of JB...,39.24,Fighting Fate (Fighting #6),6390772a3094939d
998,1,My Happily Ever After was turning into a livin...,28.80,Forever Rockers (The Rocker #12),e564c3f1a93ccf2e
999,1,Mary Shelley began writing Frankenstein when s...,38.00,Frankenstein,a492f49a3e2b6a71

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   avaibility   1000 non-null   int64
 1   description  998 non-null    object
 2   price        1000 non-null   float64
 3   title        1000 non-null   object
 4   upc          1000 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 39.2+ KB

In [11]:
df['description'] = df['description'].apply(lambda x: str(x).strip())
df

,avaibility,description,price,title,upc
0,19,Aaron Ledbetter’s future had been planned out ...,17.46,Set Me Free,ce6396b0f23f6ecc
1,19,Libertarianism isn't about winning elections; ...,51.33,Libertarianism for Beginners,a18a4f574854aced
2,19,"“Wherever you go, whatever you do, just . . . ...",45.17,It's Only the Himalayas,a22124811bfa8350
3,19,This is the never-before-told story of the mus...,57.25,Our Band Could Be Your Life: Scenes from the A...,deda3e61b9514b83
4,19,This book is an important and complete collect...,20.66,Shakespeare's Sonnets,30a7f60cd76ca58c
...,...,...,...,...,...
995,1,"To the dismay of religious leaders, study afte...",28.42,Choosing Our Religion: The Spiritual Lives of ...,a812f6969ddf3e39
996,1,Meet Bridget Jones—a 30-something Singleton wh...,29.82,Bridget Jones's Diary (Bridget Jones #1),a2b4b685dfa94733
997,1,***BONUS CONTENT: The first two chapters of JB...,39.24,Fighting Fate (Fighting #6),6390772a3094939d
998,1,My Happily Ever After was turning into a livin...,28.80,Forever Rockers (The Rocker #12),e564c3f1a93ccf2e
999,1,Mary Shelley began writing Frankenstein when s...,38.00,Frankenstein,a492f49a3e2b6a71